language: python
python:
  - "2.7"

before_install:
  - gcc -v
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo update-alternatives --remove-all gcc 
  - sudo update-alternatives --remove-all g++
  - sudo apt-get install -qq g++-4.8 gcc-4.8
  - alias gcc=gcc-4.8
  - alias g++=g++-4.8
  - gcc -v
  - sudo apt-get install -qq opencl-headers;
  - bash .travis/amd_sdk.sh;
  - tar -xjf AMD-SDK.tar.bz2;
  - AMDAPPSDKROOT=${HOME}/AMDAPPSDK;
  - export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors;
  - mkdir -p ${OPENCL_VENDOR_PATH};
  - sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT};
  - echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
  - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH};
  - export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
  - chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
  - ${AMDAPPSDKROOT}/bin/x86_64/clinfo;
  - echo "HUHU"
  - ls ${AMDAPPSDKROOT}/lib/x86_64/*
  - echo ${LD_LIBRARY_PATH}

install:
  - pip install .

