language: python

branches:
  only:
    - develop


matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
    # - os: linux
    #   python: 3.5
    # - os: linux
    #   python: 3.6

install:
  - conda install -c conda-forge pybind11 
  - conda install -c conda-forge pyopencl 
  - pip install .

script:
  - pytest -v -s --durations=50 