language: python

branches:
  only:
    # - master
    - develop


matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
    # - os: linux
    #   python: 3.5
    # - os: linux
    #   python: 3.6

install: 
  - pip install .

script:
  - pytest -v -s --durations=50 